### ISSUE TITLE
Topic are jumping around

### ISSUE THREAD

**Issue by cournof** [ottopaulsen/MMM-MQTT#25]
Hi, I just pulled the latest update (I was 2 behind) and now the topic are jumping around.  I`m using to instances of the module in my config.js.  With the previous version everything was just fine, but now the topic are jumping up and down in the column and the entire column is also blanking at times    

Here is one of the instances :

{
    module: 'MMM-MQTT',
    position: 'top_right',
    header: 'Environnement',
    config: {
        mqttServers: [
            {
                address: '192.168.2.3',  // Server address or IP address
                port: '1883',          // Port number if other than default
              //  user: 'user',          // Leave out for no user
              //  password: 'password',  // Leave out for no password
                subscriptions: [
                {
                        topic: 'home/maitre/motion', // Topic to look for
                        label: 'Chambre des Maitres :', // Displayed in front of value
                        suffix: '',        // Displayed after the value
                        decimals: 0,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
   
                {
                        topic: 'home/maitre/temp', // Topic to look for
                        label: '- Temperature :', // Displayed in front of value
                        suffix: '°C',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
		{
                        topic: 'home/maitre/hum', // Topic to look for
                        label: '- Humidite :', // Displayed in front of value
                        suffix: '%',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                     },
                {
                        topic: 'home/nil', // Topic to look for
                        label: 'Chambre Shinedown :', // Displayed in front of value
                        suffix: '',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
   
                {
                        topic: 'home/shndwn/temp', // Topic to look for
                        label: '- Temperature :', // Displayed in front of value
                        suffix: '°C',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
		{
                        topic: 'home/shndwn/hum', // Topic to look for
                        label: '- Humidite :', // Displayed in front of value
                        suffix: '%',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                     },
                {
                        topic: 'home/nil', // Topic to look for
                        label: 'Chambre Invite :', // Displayed in front of value
                        suffix: '',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
   
                {
                        topic: 'home/invite/temp', // Topic to look for
                        label: '- Temperature :', // Displayed in front of value
                        suffix: '°C',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
		{
                        topic: 'home/invite/hum', // Topic to look for
                        label: '- Humidite :', // Displayed in front of value
                        suffix: '%',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                     },
               {
                        topic: 'home/nil', // Topic to look for
                        label: 'Salon :', // Displayed in front of value
                        suffix: '',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
   
                {
                        topic: 'home/salon/temp', // Topic to look for
                        label: '- Temperature :', // Displayed in front of value
                        suffix: '°C',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
		{
                        topic: 'home/salon/hum', // Topic to look for
                        label: '- Humidite :', // Displayed in front of value
                        suffix: '%',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                     },
               {
                        topic: 'home/nil', // Topic to look for
                        label: 'Sejour :', // Displayed in front of value
                        suffix: '',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
   
                {
                        topic: 'home/sejour/temp', // Topic to look for
                        label: '- Temperature :', // Displayed in front of value
                        suffix: '°C',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
		{
                        topic: 'home/sejour/hum', // Topic to look for
                        label: '- Humidite :', // Displayed in front of value
                        suffix: '%',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                     },

               {
                        topic: 'home/nil', // Topic to look for
                        label: 'Sous-sol :', // Displayed in front of value
                        suffix: '',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
   
                {
                        topic: 'home/ss/temp', // Topic to look for
                        label: '- Temperature :', // Displayed in front of value
                        suffix: '°C',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
		{
                        topic: 'home/ss/hum', // Topic to look for
                        label: '- Humidite :', // Displayed in front of value
                        suffix: '%',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                     },
               {
                        topic: 'home/nil', // Topic to look for
                        label: 'Garage :', // Displayed in front of value
                        suffix: '',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
   
                {
                        topic: 'home/garage/temp', // Topic to look for
                        label: '- Temperature :', // Displayed in front of value
                        suffix: '°C',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                    },
		{
                        topic: 'home/garage/hum', // Topic to look for
                        label: '- Humidite :', // Displayed in front of value
                        suffix: '%',        // Displayed after the value
                        decimals: 1,         // Round numbers to this number of decimals
                        sortOrder: 30,       // Can be used to sort entries in the same table
                        maxAgeSeconds: 60    // Reduce intensity if value is older
                     },

                ]
            }
        ],

    }
},

**Comment by ottopaulsen** [comment]
I see you have the same sortOrder on all topics. Try to set all different, in the order you want them. I just fixed so sorting is working, so that is probably the reason. Please let me know how it goes.

**Comment by cournof** [comment]
Hi !!  Thanks for your quick reply. I actually already changed  the sortOrder after posting the message.  The items now start at 1 and incremented by one for each item.   It is now better but the 2 first items with data ( the only ones with data for the time being) still switch back and forth even if they are sortOrder 2 and 3 (they move faster than data is updated), also there are 2 other topics which are out of the proper order (There is 20 topics in this instance).  My second instance  seems to be OK. For test purposes I use the same 2 topics and they do not move around (but I have only 6 topics in this instance)

**Comment by ottopaulsen** [comment]
Thanks for reporting. I found a probable cause - a bug that would appear only when there are more than 10 items, as you have. I am not at home to try, but I just committed a change that may fix it. Please try and let me know.

**Comment by ottopaulsen** [comment]
By the way - you may reduce your config file size by removing all the comments behind each config item.

**Comment by cournof** [comment]
Hi, Thanks again !!   I pulled your new update.  It stopped the 2 first topics from changing order all the time.  But the other items are still not in the proper order, even with proper sortOrder values.  I did remove all the comments from the MMM-MQTT block within the config.js file but this did not help getting the other items in order.

**Comment by ottopaulsen** [comment]
Ok, I found one more bug in the sorting code. Just uploaded a patch,

If it stille does not work, can you please submit your current config so I can see? And also a screenshot showing how they appear.

Otto

**Comment by cournof** [comment]
Hi !!  You nailed it, it is now working properly !!  Thank you very much for your time.

This morning I had pulled an update that did not change the topic order, as a temporary fix, I had commented out the sortOrder from the config.js file and it solve the issue. 

But after your last update I brought back my previous version of the config.js with the sortOrder attribute and now the order is OK. 

Thanks again .

Francois
